# This workflow will create a container image and publish it to ghcr.io
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-docker-images

name: Create and publish a container image
run-name: ${{ github.actor }} is creating and publishing a container image
on:
  push:
    tags: ['[0-9]+.[0-9]+.[0-9]+']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: pia-frontend

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - dockerfile: ./docker/cnil-pia-front/Dockerfile
            image: ghcr.io/tguyader/pia-front
            tags: ghcr.io/tguyader/pia-front:stable
          - dockerfile: ./docker/cnil-pia-back/Dockerfile
            image: ghcr.io/tguyader/pia-back
            tags: ghcr.io/tguyader/pia-back:stable

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for the container
        id: meta
        uses: docker/metadata-action@v4.6.0
        with:
          images: ${{ matrix.image }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4.2.1
        with:
          context: .
          file: ${{ matrix.dockerfile }}
          push: true
          tags: ${{ matrix.tags }}
          labels: ${{ steps.meta.outputs.labels }}
